"""add oss_file_cache table

Revision ID: 00580e5e675a
Revises: 00dc39857e92
Create Date: 2026-08-05 17:25:33.928946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00580e5e675a'
down_revision: Union[str, Sequence[str], None] = '00dc39857e92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oss_file_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('local_path', sa.String(length=500), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('oss_url', sa.String(length=500), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('uploaded_at', sa.Integer(), nullable=False),
    sa.Column('expire_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_oss_cache_expire', 'oss_file_cache', ['expire_at'], unique=False)
    op.create_index('idx_oss_cache_hash_model', 'oss_file_cache', ['file_hash', 'model_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_oss_cache_hash_model', table_name='oss_file_cache')
    op.drop_index('idx_oss_cache_expire', table_name='oss_file_cache')
    op.drop_table('oss_file_cache')
    # ### end Alembic commands ###
