"""add visual_style_id to projects table

Revision ID: 00dc39857e92
Revises: e9c8cffe2ba1
Create Date: 2026-08-05 16:29:44.578451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00dc39857e92'
down_revision: Union[str, Sequence[str], None] = 'e9c8cffe2ba1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # Only drop oss_file_cache if it exists
    if 'oss_file_cache' in inspector.get_table_names():
        op.drop_index(op.f('idx_oss_cache_expire'), table_name='oss_file_cache')
        op.drop_index(op.f('idx_oss_cache_hash_model'), table_name='oss_file_cache')
        op.drop_table('oss_file_cache')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visual_style_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_projects_visual_style', 'visual_styles', ['visual_style_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint('fk_projects_visual_style', type_='foreignkey')
        batch_op.drop_column('visual_style_id')

    op.create_table('oss_file_cache',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('local_path', sa.VARCHAR(length=500), nullable=False),
    sa.Column('file_hash', sa.VARCHAR(length=64), nullable=False),
    sa.Column('oss_url', sa.VARCHAR(length=500), nullable=False),
    sa.Column('model_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('uploaded_at', sa.INTEGER(), nullable=False),
    sa.Column('expire_at', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_oss_cache_hash_model'), 'oss_file_cache', ['file_hash', 'model_name'], unique=1)
    op.create_index(op.f('idx_oss_cache_expire'), 'oss_file_cache', ['expire_at'], unique=False)
    # ### end Alembic commands ###
