"""add chat type to generate_task and add parent_ids field

Revision ID: 9ca334b83732
Revises: b21bc58ed015
Create Date: 2026-08-11 15:24:03.243782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ca334b83732'
down_revision: Union[str, Sequence[str], None] = 'b21bc58ed015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generate_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_ids', sa.String(length=500), nullable=False, server_default=''))

    # 移除 server_default（仅用于初始化）
    with op.batch_alter_table('generate_tasks', schema=None) as batch_op:
        batch_op.alter_column('parent_ids', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generate_tasks', schema=None) as batch_op:
        batch_op.drop_column('parent_ids')
    # ### end Alembic commands ###
