"""add_storyboard_takes_table

Revision ID: c3297f920733
Revises: d9e13c0efe2f
Create Date: 2026-08-12 16:03:11.362200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3297f920733'
down_revision: Union[str, Sequence[str], None] = 'd9e13c0efe2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storyboard_takes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('storyboard_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('media_file_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['storyboard_id'], ['storyboard.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_take_storyboard', 'storyboard_takes', ['storyboard_id', 'number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_take_storyboard', table_name='storyboard_takes')
    op.drop_table('storyboard_takes')
    # ### end Alembic commands ###
