"""simplify indexes keep only caller and project_caller composite indexes

Revision ID: d9e13c0efe2f
Revises: a1b2c3d4e5f6
Create Date: 2026-08-12 09:31:38.997856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9e13c0efe2f'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generate_tasks', schema=None) as batch_op:
        batch_op.drop_index('idx_generate_task_completed')
        batch_op.drop_index('idx_generate_task_project_id')
        batch_op.drop_index('idx_generate_task_provider_task_id')
        batch_op.drop_index('idx_generate_task_type')
        batch_op.create_index('idx_generate_task_project_caller', ['project_id', 'caller_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generate_tasks', schema=None) as batch_op:
        batch_op.drop_index('idx_generate_task_project_caller')
        batch_op.create_index('idx_generate_task_type', ['type'], unique=False)
        batch_op.create_index('idx_generate_task_provider_task_id', ['provider_task_id'], unique=False)
        batch_op.create_index('idx_generate_task_project_id', ['project_id'], unique=False)
        batch_op.create_index('idx_generate_task_completed', ['completed'], unique=False)
    # ### end Alembic commands ###
