"""add voice tone fields to character tables

Revision ID: da5ede4ea6a3
Revises: 538fc50dfbdb
Create Date: 2026-08-07 09:11:37.403976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da5ede4ea6a3'
down_revision: Union[str, Sequence[str], None] = '538fc50dfbdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character_history', sa.Column('voice_tone', sa.Text(), nullable=False, server_default=''))
    op.add_column('character_history', sa.Column('voice_reference_file', sa.Text(), nullable=False, server_default=''))
    op.add_column('characters', sa.Column('voice_tone', sa.Text(), nullable=False, server_default=''))
    op.add_column('characters', sa.Column('voice_reference_file', sa.Text(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'voice_reference_file')
    op.drop_column('characters', 'voice_tone')
    op.drop_column('character_history', 'voice_reference_file')
    op.drop_column('character_history', 'voice_tone')
    # ### end Alembic commands ###
