"""add project_id to generate_tasks

Revision ID: f28dbf5d457b
Revises: 9ca334b83732
Create Date: 2026-08-12 09:25:40.556087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f28dbf5d457b'
down_revision: Union[str, Sequence[str], None] = '9ca334b83732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generate_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))
        batch_op.create_index('idx_generate_task_project_id', ['project_id'], unique=False)
        batch_op.create_foreign_key('fk_generate_tasks_project_id', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generate_tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_generate_tasks_project_id', type_='foreignkey')
        batch_op.drop_index('idx_generate_task_project_id')
        batch_op.drop_column('project_id')
    # ### end Alembic commands ###
